### ISSUE TITLE
Nemo portal not working on 2.5

### ISSUE THREAD

**Issue by Rymicka** [n0xa/m5stick-nemo#101]
The Wi-Fi appears but the web page does not launch 
Device: M5stickc plus
Flashed with: esp.huhn.me
File type: .bin
No SD card

**Comment by bmorcelli** [comment]
Hi, there were a misplaced curly brackets at portal_loop function.. I've just opened a pull request to fix this.

**Comment by n0xa** [comment]
fixed in main #107
