### ISSUE TITLE
Nemo Portal don't redirect to captive portal (CardPuter)

### ISSUE THREAD

**Issue by arm-ARMY** [n0xa/m5stick-nemo#102]
In version 2.5.0, when Nemo portal is selected, the network shows up but when client try to connect it it says there's no WiFi, and don't redirect do captive portal. I'm using a Cardputer. Tried just burning the .bin file. Do not redirect to captive portal. Compiled with ardiuno-cli and build and merge with esptool.py. Same results. 

But if I Scan Network, clone an SSID then change the name it works! You get redirected to the captive portal.

**Comment by bmorcelli** [comment]
Hi, there were a misplaced curly brackets at portal_loop function.. I've just opened a pull request to fix this.

**Comment by n0xa** [comment]
fixed in main #107
