### ISSUE TITLE
v2.5.0 wifi captive portal on m5stckc_plus does not redirect to "login url"

### ISSUE THREAD

**Issue by lmichoux** [n0xa/m5stick-nemo#103]
I double checked everything. tag v2.4.1 OK   tag 2.5.0 NOTOK
the problem is that somehow when switching to the captive wifi, the automatic login page does not pop up

I am using windows10.
#define STICK_C_PLUS
#define LANGUAGE_EN_US

also, I tested manual update for DEAUTH as well as install-prerequisites.bat
file is updated correctly.

I swiched back to v2.4.1 and all is ok.

**Comment by bmorcelli** [comment]
Hi, there were a misplaced curly brackets at portal_loop function.. I've just opened a pull request to fix this.

**Comment by lmichoux** [comment]
> Hi, there were a misplaced curly brackets at portal_loop function.. I've just opened a pull request to fix this.

Great more eyes were needed, I checked the diff but I did not see it. Great job!

**Comment by n0xa** [comment]
Fixed in main #107
