### ISSUE TITLE
More bluetooth functions, easy to add

### ISSUE THREAD

**Issue by Moz1987it** [n0xa/m5stick-nemo#108]
https://github.com/tobozo/ESP32-BLEBeaconSpam

This is a simple Bluetooth spammer, same function can be found in marauder, wich also has a Samsung devices crash\spammer using Samsung watch bluetooth pairing packets, vulnerability found by https://github.com/Spooks4576

**Comment by Niximkk** [comment]
What if, instead of a Issue, you open a pull request?

**Comment by Moz1987it** [comment]
> What if, instead of a Issue, you open a pull request?

So that's what pull request are, sorry my bad I'll close this and open a pull request (I'm new to GitHub)
