### ISSUE TITLE
Booting image/sfx

### ISSUE THREAD

**Issue by GitLunatic** [n0xa/m5stick-nemo#133]
I'm sorry but the booting image is terribly low quality , and the colored background of it makes it look even worse as the background of the rest of the menu's is black (unless you change it in settings), also the booting sound should be configurable (as in ON/OFF) i feel like if you're trying to be "stealthy" a Super Mario soundtrack intro whenever you turn on your device wouldn't be of favor.

Feedback from M5StickC+2.

**Comment by bmorcelli** [comment]
Hi,

About the song, I opened a PR to make it silent.. you can get the beta in my [fork](https://github.com/bmorcelli/m5stick-nemo/releases/tag/2.6.1b)

 You can download the bin and upload using web.esphome.io

**Comment by n0xa** [comment]
The "song" thing has been on my nerves as well. I am probably going to completely gut it. It was added along with a useful PR and I let it slide but I agree, it doesn't need to be there. Regarding the boot up image, maybe I'll make it configurable but you have 320x240 pixels and you can only do so much with that.
