### ISSUE TITLE
Ideas for firmware

### ISSUE THREAD

**Issue by marl0nx** [n0xa/m5stick-nemo#141]
Add NFC/RFID and RF (433mhz) support. You could list it in the UI as soon as a supported grove module is connected. 

Features like
- NFC reader/writer/saver
- RF reader/sender/saver

**Comment by Ademolght** [comment]
it's a good idea

**Comment by n0xa** [comment]
I don't have these modules to test with, but there's also no good way to store RFID, NFC and RF data that's captured for replay, and limited program memory for built-in payloads. It feels like this is trying to do more with the M5Stick than it can really do. It might be fun to build your own Cardputer firmware to handle these, but I don't think this will fit into NEMO that well.
