### ISSUE TITLE
Question about building from source: How did you get the matrix for the image?

### ISSUE THREAD

**Issue by Awlexegrecki** [n0xa/m5stick-nemo#144]
I want to change the image, but I have no clue on how you got the almost 5000-line matrix of pixels.

**Comment by harrytrinh9** [comment]
You can change to your own image by convert it to bytes array, there are a lot of tools to do that.
Here's online tool powered by LVGL: 
[https://lvgl.io/tools/imageconverter_v9](url)

**Comment by n0xa** [comment]
I personally used lcd-image-converter: https://github.com/riuson/lcd-image-converter

But @harrytrinh9 is correct, there are a lot of tools that do the same thing, and the LVGL online one looks much easier than what I did.
