### ISSUE TITLE
not an issue just a small question can Nemo run on any esp32?

### ISSUE THREAD

**Issue by AboodeDaBOSS** [n0xa/m5stick-nemo#148]

**Comment by auburn5** [comment]
no

**Comment by AboodeDaBOSS** [comment]
why isn't all of them are esp32

**Comment by n0xa** [comment]
NEMO makes extensive use of M5Stack specific libraries, particularly around the buttons, keyboard, and displays found on these devices. You could possibly build an esp32 with the exact same display, peripherals, buttons, and whatnot that the M5Stack devices have, and then Nemo might work fine on something like that. But it will not work on generic homebrew ESP32 devices without a lot of changes.
