### ISSUE TITLE
Wifi scan portal

### ISSUE THREAD

**Issue by azrael-tzel** [n0xa/m5stick-nemo#149]
Hello, i tried the portal on my own network. 

I tried to check the https://172.0.0.1/creds

And i cant connect to the site, even when im on the same network on my phone. 

Am i doing something wrong maybe?

**Comment by noonlyy** [comment]
you need to be connected to the network that was created on the portal to be able to access the creds and ssid

**Comment by azrael-tzel** [comment]
Yes, it worked! So i close this topic now. Thanks for reacting
