### ISSUE TITLE
Add Silent mode

### ISSUE THREAD

**Issue by StingerFingersinmyass** [n0xa/m5stick-nemo#157]
I think there is a possibility to add the so-called "Silent Mode". It will allow you to use the gadget without the sound of turning it on, pressing buttons, etc.

**Comment by n0xa** [comment]
I think we complely disabled the music at boot on all platforms. That leaves NEMO Portal making a small beep when someone enters a password as the only remaining source of speaker noise. I think we can make a toggle for that. Are you suggesting that the button clicks themselves are also too loud? How do you propose we fix that, if so?
