### ISSUE TITLE
ADD possibility to add remote 

### ISSUE THREAD

**Issue by Hugop6918** [n0xa/m5stick-nemo#159]
it would be cool to add the possibility of adding lesser known remote control signals yourself with a special section thanksss

**Comment by adsflkj** [comment]
That would be cool

**Comment by n0xa** [comment]
I merged in a PR with some additional custom codes. Through this, you could create a PR to add new codes to the custom region. These devices don't have an IR Receiver so NEMO doesn't have code to parse or replay existing IR Remotes yet.
