### ISSUE TITLE
Compilation error: exit status 1

### ISSUE THREAD

**Issue by Mrclean0091** [n0xa/m5stick-nemo#172]
I get this error when i compile Nemo:

c:/users/jeanc/appdata/local/arduino15/packages/m5stack/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\jeanc\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.1.1/tools/sdk/esp32/lib\libnet80211.a(ieee80211_output.o): in function `ieee80211_raw_frame_sanity_check':
(.text.ieee80211_raw_frame_sanity_check+0x5c): multiple definition of `ieee80211_raw_frame_sanity_check'; sketch\m5stick-nemo.ino.cpp.o:C:\Users\jeanc\Desktop\m5stick-nemo/deauth.h:19: first defined here
collect2.exe: error: ld returned 1 exit status
Multiple libraries were found for "SD.h"
  Used: C:\Users\jeanc\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.1.1\libraries\SD
  Not used: C:\Users\jeanc\AppData\Local\Arduino15\libraries\SD
Using library M5StickCPlus2 at version 1.0.1 in folder: C:\Users\jeanc\Documents\Arduino\libraries\M5StickCPlus2 
Using library M5Unified at version 0.1.14 in folder: C:\Users\jeanc\Documents\Arduino\libraries\M5Unified 
Using library M5GFX at version 0.1.15 in folder: C:\Users\jeanc\Documents\Arduino\libraries\M5GFX 
Using library EEPROM at version 2.0.0 in folder: C:\Users\jeanc\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.1.1\libraries\EEPROM 
Using library IRremoteESP8266 at version 2.8.6 in folder: C:\Users\jeanc\Documents\Arduino\libraries\IRremoteESP8266 
Using library DNSServer at version 2.0.0 in folder: C:\Users\jeanc\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.1.1\libraries\DNSServer 
Using library WiFi at version 2.0.0 in folder: C:\Users\jeanc\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.1.1\libraries\WiFi 
Using library WebServer at version 2.0.0 in folder: C:\Users\jeanc\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.1.1\libraries\WebServer 
Using library ESP32 BLE Arduino at version 2.0.0 in folder: C:\Users\jeanc\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.1.1\libraries\BLE 
Using library FS at version 2.0.0 in folder: C:\Users\jeanc\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.1.1\libraries\FS 
Using library SD at version 2.0.0 in folder: C:\Users\jeanc\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.1.1\libraries\SD 
Using library SPI at version 2.0.0 in folder: C:\Users\jeanc\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.1.1\libraries\SPI

**Comment by gotyion0** [comment]
Same here :/

**Comment by Dlazder** [comment]
You just need to run script that install the dependencies. Check this path deauth_prerequisetes/install_prerequisetes.bat
