### ISSUE TITLE
Portals

### ISSUE THREAD

**Issue by eddyizm** [n0xa/m5stick-nemo#173]
Is there a way to add portals, say from evil portals ?

**Comment by danny8972** [comment]
Evil portal is already added if you scan and then select a Wi-Fi network you can clone and deauth it

**Comment by eddyizm** [comment]
ok, sweet. still waiting on the hardware to come in, a friend demo'd the google captive portal and didn't see other options in my brief look through the code.

**Comment by danny8972** [comment]
Glad to help

**Comment by eddyizm** [comment]
@danny8972 So it looks like this repo only has one portal, what I was looking for the ability to throw up a different portal like the [pineapple](https://github.com/kleo/evilportals) device. When I get mine I'll fork it and try to add a new one as the html is trivial.

**Comment by danny8972** [comment]
Ah sorry for the confusion I see what you mean now. That would be a great thing to add.

**Comment by pinhoone** [comment]
The possibility to select a portal would be amazing, I already use this function in my Flipper, do you know a way to set up my custom portal in Nemo?

**Comment by eddyizm** [comment]
@pinhoone looking through the code it looks like we would need at least 2 steps. 
1.  a menu item for selecting a portal as opposed to going to the default one and 
2.  adding the html/css/etc in the code for each additional one. This one we should be able to leverage other portal repos. 

Will give this a try when I get my hardware. Waiting on delivery :-)
