### ISSUE TITLE
compilation takes AGES

### ISSUE THREAD

**Issue by kubilay-dev** [n0xa/m5stick-nemo#182]
hey, i set up nemo in arduino ide and i can compile and upload everything works but its taking literal ages to recompile. is there any way to make this faster? when im working on changing something waiting 10min~ just for testing stuff is really tough especially if you really just need to test and play around with stuff.

i already upped the upload speed but its more the compile process.

**Comment by Pcquifume** [comment]
hey,
I don't know how to configure Nemo in the arduino ide it doesn't work I don't understand

**Comment by vs4vijay** [comment]
Which OS you're using? Please share your platform config. I believe it is windows, and due to windows defender being run on each compiled files, compilation becomes slower. @kubilay-dev @Pcquifume

**Comment by kubilay-dev** [comment]
> Which OS you're using? Please share your platform config. I believe it is windows, and due to windows defender being run on each compiled files, compilation becomes slower. @kubilay-dev @Pcquifume

i have windows defender completely disabled with defender control. and i have no additional anti virus software installed

**Comment by Pcquifume** [comment]
Yeah I use Windows.

**Comment by Pcquifume** [comment]
but for me he doesn't even want to compile it
