### ISSUE TITLE
customysed captiv portals?

### ISSUE THREAD

**Issue by Einstein00000011** [n0xa/m5stick-nemo#186]
Hello everyone, I'm currently working on customizing the HTML and CSS of the Nemo captive portal running on an M5Stick device for a project I'm_ working on. I've explored the available documentation and resources but haven't found a clear path to achieving the level of customization I need. Help would be great or dose sombody know an alternative programm wich would alow custom captiv portals?

**Comment by Dlazder** [comment]
Hello, I don't quite understand you. What do you mean by custom portal? You can easily change the html markup of the login page.
