### ISSUE TITLE
Does it work on m5stickc plus 2 ?

### ISSUE THREAD

**Issue by ViBa-Spec0** [n0xa/m5stick-nemo#191]
Recently bought a new m5stickc plus 2 and I was just wondering if Nemo works on it

**Comment by Dlazder** [comment]
Yes, it works. But I used the m5 burner for this.

**Comment by djcasper1975** [comment]
> Yes, it works. But I used the m5 burner for this.
> 
> Updated: I just managed to download this firmware via the arduino ide, although for this I had to remove the deauth function, as it caused an error during compilation.

I have same issue.

**Comment by Dlazder** [comment]
> > Yes, it works. But I used the m5 burner for this.
> > 
> > Updated: I just managed to download this firmware via the arduino ide, although for this I had to remove the deauth function, as it caused an error during compilation.
> 
> I have same issue.

Run the script to install dependencies, it is in the folder in the repository sources. After reboot your PC.
