### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by grdashark** [n0xa/m5stick-nemo#22]
Hi mate, can you add an android ble spam feature or Google Fast Pair Service spammer? Thanks!

**Comment by n0xa** [comment]
I found the flipper Xtreme Firmware Implementation, but it's fairly bloated for this project. I'll have to figure out how this protocol works at a low level and then work to boil it down to something that is more appropriate for the minimal interface I've got here.  I'll add it to the list of potential features.

**Comment by IMXNOOBX** [comment]
Well, it isnt too diferent from the the other ble spams, just changing the brand and some other tweaks in the packets will work. You can check my implementation of it below, if you want i can try to implement it nemo.

https://github.com/IMXNOOBX/fstick/blob/b1d38a5a348369a4c65aac78a84be8c64587796d/classes/ble.h#L185-L210

**Comment by I8Pizza2Day** [comment]
Love Nemo for the M5StickC Plus, was curious if you could add the Wifi Sniffer tools of the ESP32Marauder? Keep up the Awesome work! Just starting to learn more myself. But wanting the Deauth Sniffer tools for a project in a Clean GUI like your NEMO install.

**Comment by n0xa** [comment]
This has been addressed with Pull Request #35
