### ISSUE TITLE
2.0.2 not in m5burner

### ISSUE THREAD

**Issue by SalmonSoup15** [n0xa/m5stick-nemo#25]
it just isnt there, latest version is 2.0.1, would be greatly appreciated if the latest version was uploaded to m5burner. Thanks!

**Comment by n0xa** [comment]
There's no actual feature enhancements between v2.0.1 and v2.0.2. I just moved a few things around in the codebase, mostly to fix a few things with how stuff was being displayed on the screen. You can see all of the changes if you scroll down here: https://github.com/n0xa/m5stick-nemo/compare/v2.0.1...v2.0.2

**Comment by SalmonSoup15** [comment]
Ah sorry, I thought than in 2.0.2 you fixed the thing where on the cardputer unless you just barely press the enter key, it will double click so you get into the desired menu, and then get thrown right back

**Comment by n0xa** [comment]
2.0.3 was officially released and updated in M5Burner
