### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Pufferfish1223** [n0xa/m5stick-nemo#28]
Is there any way to make the ir pin one of the gpios so I can use a more powerfull ir led. Thanks

**Comment by n0xa** [comment]
I moved the IR LED pin number to the DEFINE blocks so it should be easier to compile it for a custom pin. You may need to play with the ACTIVE_LOW_IR option, some external LED attachments need that defined, others need it removed. Your most likely option is to use pin G26 on the M5Stick C Plus. If you have very good results increasing the distance with a specific add-on LED, let me know which module you're using. If it's popular enough, I can add a setting option for external LED boards if we have a known one that works well. I can't invest effort into that until I know it works really well.

**Comment by Pufferfish1223** [comment]
It worked, thank you so much, the range is now atleast 10 meters just using a generic ir led salvaged from a old remote.

**Comment by I8Pizza2Day** [comment]
@Pufferfish1223 How do you have the ir Led attached? any pics or drawings?

**Comment by Pufferfish1223** [comment]
The negative lead of the ir led is plugged in to the GND port and the positive is plugged into the G26 port of the m5stickc plus.
![WIN_20231221_18_02_02_Pro](https://github.com/n0xa/m5stick-nemo/assets/153720611/f9b64b43-7056-4ecc-8412-f103566409e6)

**Comment by n0xa** [comment]
I will likely make this more easily configurable in an upcoming release.
