### ISSUE TITLE
StickC Plus2 ir stays turned on when exiting TV B-Gone menu

### ISSUE THREAD

**Issue by mceres** [n0xa/m5stick-nemo#47]
Installed from m5burner.
StickC Plus2 ir stays turned on when exiting TV B-Gone menu I had to turn off the stick for it to turn off.

**Comment by n0xa** [comment]
Please try version 2.3.1 or newer. I changed how the IR LED is being used. Let me know if it's working right.

**Comment by mceres** [comment]
I just tried it, it's working good now. Thanks!
