### ISSUE TITLE
Evil Portal doesn't work

### ISSUE THREAD

**Issue by hunt3rbb666NotFound** [n0xa/m5stick-nemo#52]
Evil Portal doesn't work. The number of victims is not loaded and it is not possible to see the results in 172.0.0.1/creds because it is empty. I don't use SD card but I think it's not a problem. Could you fix it please? This project is really beautiful.

**Comment by n0xa** [comment]
There's a pretty serious bug in the login HTML. I'm pushing a patch (2.3.1) now.
