### ISSUE TITLE
version 2.3.1 does not work.

### ISSUE THREAD

**Issue by hunt3rbb666NotFound** [n0xa/m5stick-nemo#54]
Patch version 2.3.1 does not work. After flashing black screen and nothing else.

**Comment by dg123445** [comment]
Patch version 2.3.1 does not work. After flashing black screen and nothing else.

**Comment by n0xa** [comment]
Stick C Plus 3.2.1 image was corrupted. There's a pre-release of 2.3.2 on M5Burner for the Stick C Plus if you refresh it. This also has the improved wifi spam. I'll have official builds out today or tomorrow.
