### ISSUE TITLE
Wifi hack for stealing creds is in Spanish for some reason 

### ISSUE THREAD

**Issue by galileoleosolis** [n0xa/m5stick-nemo#58]
No clue why but I tried it and it's in Spanish

**Comment by chr0m1ng** [comment]
If you're talking about the Evil Portal it might be in Portuguese (not spanish). You have to comment/uncomment the line that defines the language at `m5stick-nemo.ino` file.

```ino
// -=-=- NEMO Portal Language -=- Thanks, @marivaaldo! -=-=-
#define LANGUAGE_EN_US
//#define LANGUAGE_PT_BR
```

**Comment by n0xa** [comment]
if you downloaded it from M5Burner or the release binaries here on GitHub, there's a PT_BR version and a normal version for several of the builds. Be sure to NOT download the PT_BR version if you prefer the portal to be in US English vs Brazilian Portuguese.
