### ISSUE TITLE
M5StickC-Plus2

### ISSUE THREAD

**Issue by ClassyPineapple** [n0xa/m5stick-nemo#65]
Does it work on the M5StickC-Plus2? I'd love to see it on the new device

**Comment by n0xa** [comment]
Yes, binaries are available for the StickC-Plus2 in each recent release, and the M5Burner also has the latest release versions available for download for the Plus2 as well.

**Comment by ClassyPineapple** [comment]
Oh thank you

**Comment by zloneotm** [comment]
Any way to solve black screen?

**Comment by n0xa** [comment]
The screen is probably just very dim. If you're using the correct firmware, try going to a dark room so you can see the screen, then adjust brightness settings.
