### ISSUE TITLE
Ajuste caso tentem deployar pelo Arduino IDE

### ISSUE THREAD

**Issue by WODIM-KEVIN** [n0xa/m5stick-nemo#67]
Na linha 71 do arquivo songs.h falta um ;
Na linha 481 do arquivo m5stick-nemo falta um T na variável XT_ROTATION, o correto seria TXT_ROTATION

**Comment by Niximkk** [comment]
Abre um pull request arrumando :)

**Comment by n0xa** [comment]
This was fixed.
