### ISSUE TITLE
How to turn on backlight (after it fades) without exiting the NEMO portal ?

### ISSUE THREAD

**Issue by hugows** [n0xa/m5stick-nemo#90]

**Comment by n0xa** [comment]
This is a bug and I was going to self-report it. 

At the end of `void portal_loop()`  I need to make a throwaway call to `check_select_press()`  so that pressing the M5 button will bring the display back. I'll get this worked into the next release because it's also driving me nuts.

**Comment by n0xa** [comment]
this is finally fixed in the latest release
