### ISSUE TITLE
better ui + wifi spam issue

### ISSUE THREAD

**Issue by SzymonDevs** [n0xa/m5stick-nemo#92]
Hi,
I really like this project, and am using it on my StickC Plus. Everything's good, but in my opinion the ui is looking a bit outdated and is almost all in one color(green). I think it would be nice to make a better ui for it, like in the discontinued fstick firmware. Having to go to the settings to check battery percentage is a problem too, there's some firmware that have it on the top/status bar. Albo, for me personally it's better to see a progressbar in tv-b gone instead of some text that some people don't even understand.
Albo, I have an issue where the random wifi spam generates max. 5 network instead of spamming a lot of them like for example in the fstick or marauder firmware.
Regards,
Szymon(and if something's wrong sorry for my english)

**Comment by n0xa** [comment]
I'm not terribly concerned about the UI. The FStick UI was very glitchy, and the esp32 marauder menu is also very hard to read and small. I would like to add some color customization and I could possibly make the selected item inverted color. I'll think about it. 

I've noticed wifi spam hasn't been working too well lately, too. The latest release makes wifi spam much more aggressive and it seems to be getting a lot more hits on the SSID list. Take it for a spin.
