### ISSUE TITLE
alternetive update method

### ISSUE THREAD

**Issue by ga1pi2** [n0xa/m5stick-nemo#97]
Hello,
if possible can you please link this tool: https://espressif.github.io/esptool-js/ as another option for people who want to flash the image directly from this github but dont have the toolchain required

the instructions are the same just in a nice web interface on a chromium browser

**Comment by n0xa** [comment]
I hadn't seen that tool before, but I was contemplating showing how to do it with SpaceHuhn's WEB ESP tool. I'll try to come up with something in the readme when I have time.
