### ISSUE TITLE
NEMO Portal not work 

### ISSUE THREAD

**Issue by klamath1977** [n0xa/m5stick-nemo#99]
Hello,
I have M5stickC Plus w/o sdcard and NEMO Portal not work propery. 
I can connect to m5stick wifi but portal page not appears, I have tested official build 2.5 and also I compile by myself from latest git repo with this change to M5stick-nemo.ino
 #define STICK_C_PLUS
 //#define SDCARD

The portal work perfectly with 2.4.1 and lowers build

**Comment by Rymicka** [comment]
I have the same problem on 2.5 I flashed the bin file with esp.huhn.me

**Comment by bmorcelli** [comment]
Hi, there were a misplaced curly brackets at portal_loop function.. I've just opened a pull request to fix this.
